### ISSUE TITLE
My ABB Inverter Replies on Aurora Protocol but not on ModBus RTU

### ISSUE THREAD

**Issue by muzzammilhussain** [jrbenito/canadianSolar-pvoutput#7]
I am pretty struck with aurora inverter it replies on Aurora Software did everything what manual says but it doesnt replies back on ModBus RTU

**Comment by jrbenito** [comment]
Hi @muzzammilhussain ,

ABB/Aurora inverters uses Aurora Protocol, not ModBus RTU. 

I have another repo on Aurora but it is meant to run on Arduinos, you can grab information from there. There are other softwares mentioned there that runs on Linux/RPi you can use as inspiration as well.

Worth saying that ABB sells (expensive) hardware that converts Aurora protocol to Modbus. I don't think it worth its price if you have one or two inverters only.

Cheers.
